### ISSUE TITLE
Injected code snippets

### ISSUE THREAD

**Issue by MSeal** [nteract/testbook#11]
When testing a notebook we'll want to be able to pass snippets of code to run inside the kernel. This will allow for users to write functions or text of code (when cross language) to prepare, or activate code from within the kernel.

```python
def helper():
  print("I ran in the kernel")

@testbook.notebook(path)
def test_foo(notebook):
  notebook.inject(helper)
  notebook.assert_output_text("I ran in the kernel")
```

This can be achieved by using the `inspect` module to extract the source code as text and passing it as though it were a cell to execute in the jupyter kernel.

**Comment by rohitsanj** [comment]
From https://github.com/nteract/testbook/pull/13#discussion_r402722369
> Specify what cell to inject before or after as kwargs

This should be pretty straightforward to implement! Will do in a bit.


> Reference local variables executed in earlier cells.

I guess referencing local variables in earlier cells can be done by executing those particular cells before injecting code. Or, as I mentioned in https://github.com/nteract/testbook/pull/13#discussion_r402731117, we could pass an arg called `prerun` to pre-run the specified cells.

**Comment by MSeal** [comment]
I like the pre-run idea.
