### ISSUE TITLE
Getting an InterpreterNotFoundError on running the command  tox -e py36 during setup

### ISSUE THREAD

**Issue by MuditJ** [nteract/testbook#123]
I was trying to setup this repo as per the details in https://github.com/nteract/testbook/blob/main/CONTRIBUTING.md. On running the command: tox -e py36 I get this error: ERROR:  py36: InterpreterNotFound: python3.6

I get the same issue for python 3.7 on running the tox command, although the tests for 3.8 work fine, which is the python version installed on my system. 
The docs say regarding the command tox -e py36: This will just execute the unittests against python 3.6 in a new virtual env

So do I need to install the 3.6 and 3.7 versions myself or is this done by tox? If I need to do this, what is the recommended way of doing so?

**Comment by MSeal** [comment]
Yes, you need python versions installed to run the commands for those versions. For local development just having the 3.8 commands work is fine as the PR will run the other environments.

Depending on OS you can install python 3.x with `brew install python3.6` / `sudo apt-get install python3.6` or [install pyenv](https://realpython.com/intro-to-pyenv/) and use `pyenv install python3.x.x` (more reliable path).
