### ISSUE TITLE
Handle notebook execution timeouts

### ISSUE THREAD

**Issue by rohitsanj** [nteract/testbook#14]
We need to be able to handle notebook execution timeouts.

**Comment by rohitsanj** [comment]
It seems like nbclient handles notebook execution timeouts?

@MSeal you had mentioned this a while ago, can you please shed some more light on this? :)

**Comment by MSeal** [comment]
Yeah, let's set the default timeout with our wrapper here a lot shorter (a minute?) and document how to change that default.
