### ISSUE TITLE
Return value as None from testbook function

### ISSUE THREAD

**Issue by ranjiGT** [nteract/testbook#143]
I am writing a code for auto-grading my notebook based on the **test_stdout()** example. It successfully checks the conditions as defined by `tb.cell_output_text()` but when I perform some basic operations the return value is None is what I get, instead of the variable that I pass into this function. 

Note: The below I call from a external python file to execute my notebook.

```
from testbook import testbook

@testbook('./ssnn_solved.ipynb', execute=True)
def test_stdout(tb):
    cells = [7, 13, 17, 21]
    score = 0
    for cell in cells:
        if tb.cell_output_text(cell) == 'Test passed.':
        	score += 1
    return score

res = test_stdout()
print(res)
``` 
Outputs : None

But desired:  4

**Comment by rohitsanj** [comment]
Hi @ranjiGT! Thanks for raising this bug! This was a simple fix, and I'll be raising a PR soon. :)

**Comment by rohitsanj** [comment]
Meanwhile, you could consider using the `with testbook(..) as tb` pattern instead of the decorator pattern.

**Comment by rohitsanj** [comment]
Yep, that's right! My bad :)
