### ISSUE TITLE
Remove codecov dependency

### ISSUE THREAD

**Issue by johannes-mueller** [nteract/testbook#157]
From yesterday on, the codecov package is no longer available on pypi. That makes `pip install testbook[dev]` fail as the dependency to codecov cannot be resolved.

https://about.codecov.io/blog/message-regarding-the-pypi-package/

Workaround is to use 

```sh
pip install testbook ipykernel
```

instead.

**Comment by rohitsanj** [comment]
Looks like they re-instated the `coverage` package to PyPI on Apr 17, 2023. Removed codecov as dev dependency in #158.

**Comment by johannes-mueller** [comment]
Thanks a lot.
