### ISSUE TITLE
Accept notebook as str, file and nbformat.NotebookNode object

### ISSUE THREAD

**Issue by rohitsanj** [nteract/testbook#55]
Currently, the `testbook` api only accepts a notebook path. We should extend it to also accept file objects and `nbformat.NotebookNode` objects. 

@MSeal how do you suggest we go about this?

A particular use case where this would be feasible is when a notebook is obtained through a GET request. It would need to be saved first, and then provide the path to it for testbook to work. We can avoid unnecessary file I/O by directly accepting file objects.

**Comment by MSeal** [comment]
Yeah I think that's a good addition. You can check if it's a string at first and if it's not assume it's a file-like object.
