### ISSUE TITLE
Conda build

### ISSUE THREAD

**Issue by MSeal** [nteract/testbook#60]
We need a conda-forge feedstock recipe for installing easily in conda environments.

**Comment by fcollonval** [comment]
I will do this.

Who should I add as maintainers?

**Comment by fcollonval** [comment]
XRef: https://github.com/conda-forge/staged-recipes/pull/13106

**Comment by rohitsanj** [comment]
Thank you for taking this up @fcollonval! 

You may add @MSeal and @rohitsanj (me) as maintainers.

**Comment by rohitsanj** [comment]
[Here](https://github.com/conda-forge/testbook-feedstock) is our conda-forge repo. 

Thanks again @fcollonval. Closing this issue.

**Comment by rohitsanj** [comment]
We are now on conda-forge! 🎉

Thanks again @fcollonval 

https://github.com/conda-forge/testbook-feedstock
