### ISSUE TITLE
Add `cell_execute_result` to `TestbookNotebookClient`

### ISSUE THREAD

**Issue by fcollonval** [nteract/testbook#69]
Similarly to `cell_output_text`,

https://github.com/nteract/testbook/blob/957cc4df52f055f5c403202d28281695f802c571/testbook/client.py#L137-L146

it would be nice to have a method `cell_execute_result`.

What do you think?

**Comment by rohitsanj** [comment]
Yes, for sure. However, there is an internal static method - `TestbookNotebookClient._execute_result` which does the job.

Perhaps we could implement a new function `cell_execute_result` which would internally call `_execute_result`. Let me know if you would like to take this up @fcollonval 👍

**Comment by fcollonval** [comment]
> Let me know if you would like to take this up @fcollonval 👍

Sure I'll push a PR next week.
