### ISSUE TITLE
execute_cell fails if cell takes longer than 60 seconds to run

### ISSUE THREAD

**Issue by alex-l-kong** [nteract/testbook#70]
We're testing a notebook with a cell that normally takes about 2 minutes to run. However, calling `execute_cell` on that cell gives us this error:

```
E           nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 60 seconds.
E           The message was: Cell execution timed out.
E           Here is a preview of the cell contents:
E           -------------------
E           ...
```

Is there a way we can increase the timeout threshold to more than 60 seconds?

**Comment by rohitsanj** [comment]
Hi @alex-l-kong!

Yes, you will have to pass in the `timeout` kwarg into the `testbook` API. Here is an example from both usage patterns:

```python
def my_test():
    with testbook(nb, timeout=100) as tb: # 100 seconds
        pass
```

```python
@testbook(nb, timeout=100)
def my_test(tb):
    pass
```
