### ISSUE TITLE
How can this be used as part of the github classroom autograder workflow?

### ISSUE THREAD

**Issue by wbwatkinson** [nteract/testbook#79]
I've attempted to use this utility as part of the github autograder workflow.

My attempts result in the error below. Unfortunately, I don't know enough about the environment to determine if the problem is with my GitHub workflow action, with the notebook, with how I'm creating the test file, or how I'm referencing the notebook. Thank you for any assistance you can offer.

When this is present in the test file:
```python
@testbook('simple_lr.ipynb', execute=True)
```

I get the following error:
```bash
  self = <jupyter_client.kernelspec.KernelSpecManager object at 0x7fb372f72518>
  kernel_name = 'python3'
      def get_kernel_spec(self, kernel_name):
          """Returns a :class:`KernelSpec` instance for the given kernel_name.

          Raises :exc:`NoSuchKernel` if the given kernel name is not found.
          """
          if not _is_valid_kernel_name(kernel_name):
              self.log.warning("Kernelspec name %r is invalid: %s", kernel_name,
                               _kernel_name_description)

          resource_dir = self._find_spec_directory(kernel_name.lower())
          if resource_dir is None:
  >           raise NoSuchKernel(kernel_name)
  E           jupyter_client.kernelspec.NoSuchKernel: No such kernel named python3

  /usr/local/lib/python3.6/dist-packages/jupyter_client/kernelspec.py:235: NoSuchKernel
  =========================== short test summary info ============================
  FAILED simple_lr_test.py::test - jupyter_client.kernelspec.NoSuchKernel: No s...
  ========================= 1 failed, 1 passed in 0.65s ==========================
```

**Comment by MSeal** [comment]
Sorry I missed this message earlier. Did you end up resolving the issue? It appears like you environment executing the tests didn't have a kernel registered with the matching name. Likely a result of running the test suite in an environment without your runtime dependencies.

**Comment by wbwatkinson** [comment]
That is correct, adding the following instructions to the GitHub action setup sequence resolved the problem:

```
python -m pip install ipykernel; python -m ipykernel install --user;
```

**Comment by lzkelley** [comment]
Should `ipykernel` be a package requirement for `testbook`?

**Comment by MSeal** [comment]
It might make sense atm, though in the future when more kernel are being actively used (e.g. xeus) those users will want to be able to install without the large dependency chain for ipykernel. if you use `pip install testbook[dev]` it will pull ipykernel and some other optional dependencies common to development needs as well if that's helpful.

**Comment by lzkelley** [comment]
Makes sense, thanks; I'll take a look at the [dev] option.
A brief note in the README#Installing-Testbook would be an alternative, helpful option (e.g. to avoid surprise CI failures)

**Comment by MSeal** [comment]
That is a good point, I'll look at updating that to give a better heads up. Thanks @lzkelley
