### ISSUE TITLE
Document usecases of `resolve`

### ISSUE THREAD

**Issue by loichuder** [nteract/testbook#90]
Hello,

I wanted to test the value of **variables** defined in my notebook:
```
foo = tb.ref("my_variable")
assert foo == "foo" # This fails
```
**EDIT: This works in fact. See the below comments for an accurate description of my problem**

I failed to do so as the documentation shows only examples with functions (or did I miss something ?). 
I had to dig in the code to find the `resolve()` method to do:
```
foo = tb.ref("my_variable").resolve()
assert foo == "foo" # This passes
```

Is this the recommended way of doing it ? If so, examples with `resolve` would be a helpful addition to the documentation ! :slightly_smiling_face:

**Comment by rohitsanj** [comment]
That's strange, `foo == "foo"` should work without resolving the reference object. Can you give us more details on the failure? Does it fail due to some error?

**Comment by loichuder** [comment]
You are right about `foo == "foo"`. My bad, I didn't investigate enough...

My usecase is to test for the existence of a file generated by the notebook. Let's say my output file path is stored in `output_file`.

As you said, doing something like:
```python
assert output_file == 'output.txt'
```
works but using more involved methods such as `os.path.isfile` fail:
```python
assert os.path.isfile(output_file)
```
as `os.path.isfile` expects `string, bytes, os.PathLike or integer, not TestbookObjectReference`

**Comment by rohitsanj** [comment]
Got it!

We surely do need some examples with `resolve` in our documentation. Thanks for the suggestion, and thanks for using testbook 👍

**Comment by loichuder** [comment]
I have edited my original comment and the issue name to be clearer.

Thanks for the quick reply !

**Comment by rohitsanj** [comment]
Hey @loichuder, testbook 0.4.0 now returns the actual object if it is JSON serializable, so you no longer need to resolve the reference objects.

**Comment by loichuder** [comment]
Tested: it works like a charm ! Thanks for the notice !

Feel free to close this then if examples with `resolve` are no longer relevant.
